### ISSUE TITLE
Encoding issue in test results

### ISSUE THREAD

**Issue by Kombustor** [se2p/programming-styles-ss-2020-public-tests#1]
I just received my first test results but there seems to be an encoding issue in the javascript test results:

```
[0m[0m
[0m  Basic Test[0m
[0m    runs correct version of node()[0m
    [32m  ✓[0m[90m Version of node must be v10.20.1[0m
[0m    runs without exceptions()[0m
    [31m  1) Preys and Hunters should raise no exception[0m


[92m [0m[32m 1 passing[0m[90m (10ms)[0m
[31m  1 failing[0m

[0m  1) Basic Test
       runs without exceptions()
         Preys and Hunters should raise no exception:
[0m[31m     Error: Not yet implemented[0m[90m
      at Object.main (/home/preys-and-hunters.js:3:11)
      at Context.<anonymous> (test/basic-tests.js:20:17)
[0m


[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Test failed.  See above for more details.
[0mmake[1]: *** [makefile:12: test] Error 1
make: *** [makefile:15: test] Error 2
```

As I don't know how the output is getting captured and saved I can't propose a solution, but I think the readability of the test results is really affected by this issue.

My guess would be that the language is not set to a utf-8 one, as indicated by [this](https://stackoverflow.com/questions/11809598/mocha-test-output-fonts-missing) SO post.

**Comment by alessiogambi** [comment]
Hi,

I can visualize correctly the formatted output on my console. The weird-looking characters are defining special symbols like flags and colors to highlight passing and failing tests. To create the log file I simply piped the output of mocha to the file (and this seems to be the problem [1]).

At this point, I am open to any solution which can improve readability. Starting from disabling colors to change the format of the reports.
