### ISSUE TITLE
Clean up test reports

### ISSUE THREAD

**Issue by alessiogambi** [se2p/programming-styles-ss-2020-public-tests#2]
Currently, the test reports include annoying comments/outputs from make. Getting rid of those might help readability.

**Comment by alessiogambi** [comment]
The test reports for the java task show an annoying `E` for each failed test which shall be removed. This is the output of the standard JUnit listener (which should have been disabled by now)

**Comment by Kombustor** [comment]
I guess this issue has been resolved?

**Comment by alessiogambi** [comment]
Yes, thanks. I have not idea why in some cases GitHub closes automatically the issue and in some other cases it does not...
