### ISSUE TITLE
Tests fail for no reason

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-public-tests#22]
The test cases are passing on my Windows machine (IntelliJ IDEA). However, some test cases are failing for no reason on Linux as well as on Grading System. I am not sure what is the source of the problem. This only happens for FileTest test cases. The outputs are definitely correct, maybe there are some encoding issues.

![CX](https://user-images.githubusercontent.com/17963017/81514010-cf66ce80-9341-11ea-8cf5-d0abb7cdc6ed.PNG)

**Comment by mhrimaz** [comment]
The problem was with empty char printing

**Comment by alessiogambi** [comment]
Uhmm... Do you mean the empty chars on the "right" side of the banner?

**Comment by mhrimaz** [comment]
Yes exactly. I forgot to update my code on VPS. But maybe others encounter this issue, and it is hard to debug because you can't see the character or detect any extra spacing in the output. Perhaps a test case would be helpful.

**Comment by alessiogambi** [comment]
> Perhaps a test case would be helpful.

That's the spirit !!

Probably an issue on the program-description might help as well. We might need to clarify that each screen must be rendered ENTIRELY such that all the lines, including the spaces on the right side of each line, must be printed. This way we can also check that the length of all the lines in each scree is the same.

**Comment by mhrimaz** [comment]
That's a good solution, but we need to update all the test cases, as well as inputs and outputs file. Also other students need to update their code, which I think is not a big deal.
