### ISSUE TITLE
Issue with the public tests for Javascript

### ISSUE THREAD

**Issue by stocker4141** [se2p/programming-styles-ss-2020-public-tests#25]
I am receiving some weird output from the public tests for javascript. In the actual output all lines are marked with this - sign:
```
...
      - ╔════════╤═══════╗ 
      -┌──────────────────┐
      -│     Nice tie     │
      -│       LOL!       │
      -└──────────────────┘
```
In the expected output all lines expect the last one are marked with the + sign:
```
...
      + ╔════════╤═══════╗ 
      +┌──────────────────┐
      +│     Nice tie     │
      +│       LOL!       │
      +└──────────────────┘
        ╚════════╧═══════╝
```
Lines except the last board are excluded. From my understanding this diff is trying to tell me that all lines are different, except the last one. Is that correct?
The whitespaces at the end of the lines seems to be correctly printed and the characters match.
Could it be that there is something wrong with the linebreaks in the test files?
This would explain why the last line matches since we trim the outputs from the right.

I can do some more debugging later today and come back with the index of the first difference, but i can not really explain this behaviour. Is anyone else having the same issue?

**Comment by alessiogambi** [comment]
On what platform are you developing on?
Maybe the diff says that lines that are not expected to be there are there instead?

**Comment by stocker4141** [comment]
I am developing on windows and i am using a standard console.log for printing.

The logs start with these boards respectively:
```
      -╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗
      -║  ┌──┐1 │   │   │   │   │   │ 2 │   │   │   │   │   │       ║
      -║  │  │  │   │   │   │   │   │ 3 │   │   │   │   │   │       ║
      -║  │  │  │   │   │   │   │   │ 4 │   │   │   │   │   │       ║
      -║  └──┘6 │   │   │   │   │   │ 5 │   │   │   │   │   │       ║
      -╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝
```
```
      +╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗
      +║  ┌──┐1 │   │   │   │   │   │ 2 │   │   │   │   │   │       ║
      +║  │  │  │   │   │   │   │   │ 3 │   │   │   │   │   │       ║
      +║  │  │  │   │   │   │   │   │ 4 │   │   │   │   │   │       ║
      +║  └──┘6 │   │   │   │   │   │ 5 │   │   │   │   │   │       ║
      +╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝
```
From what i can tell these boards are the same but are marked as different by the diff. I don't think there is a unexpected line there but maybe i am just failing to understand the output mocha provides. 
I don't have access to my setup right now, so i can not provide the full logs until later today.

**Comment by alessiogambi** [comment]
From what I see from the last report `1589365300` your tests pass. However, I noticed that your program might be rejecting valid inputs. For example, the basic test provides these inputs:
```var pah_inputs = [1, 2, 3]```
And your program outputs:
```
╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗ 
┌──────────────────────────────────────────────────────────────┐
│               The provided input is not valid!               │
│                      Offending input: 1                      │
└──────────────────────────────────────────────────────────────┘
 ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 
╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗ 
┌──────────────────────────────────────────────────────────────┐
│               The provided input is not valid!               │
│                      Offending input: 2                      │
└──────────────────────────────────────────────────────────────┘
 ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 
 ╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗ 
┌──────────────────────────────────────────────────────────────┐
│               The provided input is not valid!               │
│                      Offending input: 3                      │
└──────────────────────────────────────────────────────────────┘
 ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 

```

**Comment by stocker4141** [comment]
Ah thank you. The input there seems to be numbers and my program is checking for strict equality. If the input is an array of Strings, the input is treated correctly. 
Is it intended that the program is able to handle an array of numbers instead of strings as input?

I figured out what the issue was with the tests failing on my machine:
1. git was configured to auto-correct line endings "\n" <-> "\r\n"
2. As a result the text in the test data was "<line>\r\n"
3. javascripts console.log outputs only "\n" even on windows
Seems the tests are sensitive to line endings, which is a bit confusing on windows but causes no trouble on linux. 

If this behaviour with regards to line endings is intended, we can close this issue. Otherwise, maybe we can move the javascript tests to a line wise comparison as well ?
Splitting lines at the line endings would fix this problem.

**Comment by alessiogambi** [comment]
Hi, the program originally was intended to handle strings as thise are passed as input to the program. However there is no need to be strict about the input type. Regarding line endings I think it is safe to explicitly ask  for using only and only \n.
