### ISSUE TITLE
Generating test files for colored outputs

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-public-tests#41]
I noticed that @alessiogambi have implemented some tests for checking the coloring. Do you need the colored output files? It is not readable though. If such thing would be helpful please do let me know. Or if there is any help required please let us know. 

![image](https://user-images.githubusercontent.com/17963017/87406957-c7d1d900-c5c1-11ea-9a60-0c4913dbd2eb.png)

**Comment by alessiogambi** [comment]
No I do not need those files, as I have already generated them in a simplified version. Thanks
