### ISSUE TITLE
Tests stop after first failure

### ISSUE THREAD

**Issue by Kombustor** [se2p/programming-styles-ss-2020-public-tests#5]
As already explained in the exercise session I experienced that when the first private test fails the test execution stops.

Unfortunately I wasn't able to find the issue myself, so instead of creating a pull request I had to create this issue. When googling for "JUnit stops after first failed test" (and other variations) all resources I found were about the reverse problem of mine - stopping JUnit after the first failed test. But I didn't find a solution on how to NOT stop the execution after the first test fails.

**Comment by alessiogambi** [comment]
I have to look into that closely, as JUnit should *not* stop after the first test fails. Probably, it's just a matter of configuration/options

**Comment by alessiogambi** [comment]
I forcefully failed one test but the other tests execute. So maybe can you check if this is fixed?

**Comment by Kombustor** [comment]
I will report when my next test results come in.

**Comment by alessiogambi** [comment]
@Kombustor Thanks. Note that since public and private tests have exactly the same structure, you might want to try out if the same happens on public-tests (locally)?

**Comment by Kombustor** [comment]
Locally it seems to work fine now! I'm still waiting for the automatic test results (for > 1 hour now)

**Comment by alessiogambi** [comment]
There's some rebooting and maintenance going on in the faculty cluster, so I am waiting for them to put the servers online and resume with testing...

**Comment by Kombustor** [comment]
Ahh okay, thanks for the clarification!

**Comment by alessiogambi** [comment]
I managed to restart the thing only this morning. Hope. Most of the things are fixed. Note that some changes to the public tests have been merged just now... So it might take a bit before you'll see the effects on your reports.

**Comment by alessiogambi** [comment]
I close this for the moment. If you experience the same problem, we'll reopen the issue
