### ISSUE TITLE
Unable to detect color

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-public-tests#52]
This is the real output of my program

![image](https://user-images.githubusercontent.com/17963017/88034871-9452f980-cb41-11ea-9c68-2e7aca35430a.png)

however, the test program is not correctly detecting the color and instead it will pick RESET as my UI background. Probably some regexes are not correct.

![image](https://user-images.githubusercontent.com/17963017/88035031-d54b0e00-cb41-11ea-8cbc-6ed659c1db7f.png)

**Comment by alessiogambi** [comment]
@mhrimaz can you point me to the commit of your repo where you observe this behavior so I can check that out and debug? Maybe you can also take a look at the code of ColorFSM to see how/where this happens?

**Comment by mhrimaz** [comment]
the latest commit in my repo shows this behavior: https://github.com/se2p/ps-2020-assignment-03-mhrimazATTpassauUNI

Maybe the problem is that I am using reset after each character printing, so the color detector detects reset character.

**Comment by mhrimaz** [comment]
Maybe the test is not passing the color enable parameter. Or maybe I am not correctly reading it.

**Comment by alessiogambi** [comment]
I am looking into that now. I'll report here what I find

**Comment by alessiogambi** [comment]
@mhrimaz I found an issue with your code, since this is not giving away details, I describe the problem here:
The ColoredTest enables the aspect by providing the JVM flag (`-Denable.colors`). However, your program does not reliably check this because it uses `System.getProperties().contains` instead of `System.getProperties().containsKey` (lines 24 and 47).

So your program during tests generated the output without colors, and the tests correctly point that out. Once you fix this issue, also during automated tests, your program produces the colored output (and that seems to be wrong?).

I am checking that now.

**Comment by alessiogambi** [comment]
The reason for the (next) error is the following. On the final board (or when the message banner is rendered), your code produces an output where the color of the empty spaces is wrong. You set the background color to CYAN-`% ` but it should be without colors (i.e, RESET-§). This case is clearly exemplified in the program-description.

Below I report one assertion error for completeness:

```12) testInputOutputFile[11](ColoredFileTest)
java.lang.AssertionError: The Background GUI output for test tricky_example_missing is not as expected.
Expected: expected
§%%%%%%%%%%%%%%%%%%%%%%%%%%§  <<
############################
############################
############################
############################
§%%%%%%%%%%%%%%%%%%%%%%%%%%§
^
     but: was
%%%%%%%%%%%%%%%%%%%%%%%%%%%%  <<
############################
############################
############################
############################
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
^
First difference at line 156 expected: '§' got: '%'
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at ColoredFileTest.testInputOutputFile(ColoredFileTest.java:192)
```

**Comment by mhrimaz** [comment]
Oh, I didn't pay attention to that case. Thank you very much.
