### ISSUE TITLE
Handling experimental-worker flag in worker_threads

### ISSUE THREAD

**Issue by zali01-de** [se2p/programming-styles-ss-2020-public-tests#53]
For Dataspaces Style, one solution to implement threads is to use the worker_threads module. However, this module is still in the experimental phase in Node 10.20 and it is necessary to issue the --experimental-worker flag when executing the script. Therefore, it is required to find the most optimal way to handle this in _testing_.

**Comment by alessiogambi** [comment]
@zali01-de Ok. I see the problem. What's your suggestion, if you have one.

**Comment by alessiogambi** [comment]
Hi, 
I fixed this by adding the option as startup options for mocha as explained here [1].

I tested this by requiring the module and checking that node does not complain about not being able to find it. Use node 10.20.


[1] https://github.com/mochajs/mocha/issues/3670
