### ISSUE TITLE
Javascript tests only runs public tests (twice)

### ISSUE THREAD

**Issue by Kombustor** [se2p/programming-styles-ss-2020-public-tests#7]
An excerpt from `javascript.log`:

```
-----------------------------------------------
 RUNNING TESTS FROM public-tests
-----------------------------------------------

> @ test /public-tests/javascript
> mocha --no-color

[..................]

npm ERR! Test failed.  See above for more details.
-----------------------------------------------
 RUNNING TESTS FROM private-tests
-----------------------------------------------

> @ test /public-tests/javascript
> mocha --no-color
```

So I assume the public tests are run twice, probably a typo.

Off topic: Will the deadline be extended due to the many recent changes and due to the fact that the registration deadline has been extended too?

**Comment by alessiogambi** [comment]
There's no typo. At the moment, to test the integration of `private-tests`, I used a copy of the public tests, so you see the same results twice, but indeed we are running tests from two separate projects.
